# Generated by Django 4.2.5 on 2023-09-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("leaders", models.CharField(max_length=50)),
                ("emails", models.EmailField(max_length=254)),
                ("description", models.CharField(max_length=250)),
            ],
        ),
    ]
